/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ContentBlock = {
    _type: 'contentBlock';
    heading?: string;
    background?: 'white' | 'sand' | 'opal' | 'evergreen';
    body?: Array<
        | {
              children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: 'span';
                  _key: string;
              }>;
              style?:
                  | 'normal'
                  | 'h1'
                  | 'h2'
                  | 'h3'
                  | 'h4'
                  | 'h5'
                  | 'h6'
                  | 'blockquote';
              listItem?: 'bullet' | 'number';
              markDefs?: Array<{
                  href?: string;
                  _type: 'link';
                  _key: string;
              }>;
              level?: number;
              _type: 'block';
              _key: string;
          }
        | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              _type: 'image';
              _key: string;
          }
    >;
};

export type HeroBlock = {
    _type: 'heroBlock';
    heading?: string;
    subheading?: string;
    backgroundImage?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
    ctaText?: string;
    ctaLink?: string;
};

export type SiteSettings = {
    _id: string;
    _type: 'siteSettings';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    phone?: string;
    email?: string;
    address?: string;
    reviews?: {
        ratingLabel?: string;
        tripadvisorUrl?: string;
        googleUrl?: string;
    };
    socialLinks?: {
        facebook?: string;
        instagram?: string;
        youtube?: string;
        tiktok?: string;
    };
};

export type TripReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'trip';
};

export type RiverReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'river';
};

export type Homepage = {
    _id: string;
    _type: 'homepage';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    heroHeading?: string;
    heroCtaText?: string;
    heroCtaLink?: string;
    heroImage?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
    };
    featuredTrips?: Array<
        {
            _key: string;
        } & TripReference
    >;
    storyBody?: string;
    storyImageLeft?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
    storyImagePortrait?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
    storyCtaText?: string;
    storyCtaLink?: string;
    rivers?: Array<
        {
            _key: string;
        } & RiverReference
    >;
    learnContent?: Array<{
        title?: string;
        image?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
        };
        link?: string;
        isVideo?: boolean;
        _type: 'learnCard';
        _key: string;
    }>;
};

export type SanityImageCrop = {
    _type: 'sanity.imageCrop';
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityImageHotspot = {
    _type: 'sanity.imageHotspot';
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type NewsletterSubscriber = {
    _id: string;
    _type: 'newsletterSubscriber';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    email?: string;
    subscribedAt?: string;
};

export type ContactSubmission = {
    _id: string;
    _type: 'contactSubmission';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    email?: string;
    message?: string;
    submittedAt?: string;
};

export type Post = {
    _id: string;
    _type: 'post';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    excerpt?: string;
    mainImage?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
    publishedAt?: string;
    category?: 'trip-prep' | 'conservation' | 'culture-history';
    body?: Array<
        | {
              children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: 'span';
                  _key: string;
              }>;
              style?:
                  | 'normal'
                  | 'h1'
                  | 'h2'
                  | 'h3'
                  | 'h4'
                  | 'h5'
                  | 'h6'
                  | 'blockquote';
              listItem?: 'bullet' | 'number';
              markDefs?: Array<{
                  href?: string;
                  _type: 'link';
                  _key: string;
              }>;
              level?: number;
              _type: 'block';
              _key: string;
          }
        | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: 'image';
              _key: string;
          }
    >;
};

export type Slug = {
    _type: 'slug';
    current?: string;
    source?: string;
};

export type Page = {
    _id: string;
    _type: 'page';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    content?: Array<
        | ({
              _key: string;
          } & HeroBlock)
        | ({
              _key: string;
          } & ContentBlock)
    >;
};

export type Faq = {
    _id: string;
    _type: 'faq';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    question?: string;
    answer?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?:
            'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    category?:
        'general' | 'booking' | 'trip-preparation' | 'safety' | 'cancellation';
    order?: number;
};

export type ActivityReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'activity';
};

export type TripCategoryReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'tripCategory';
};

export type SanityFileAssetReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type FaqReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'faq';
};

export type Trip = {
    _id: string;
    _type: 'trip';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    river?: RiverReference;
    activities?: Array<
        {
            _key: string;
        } & ActivityReference
    >;
    categories?: Array<
        {
            _key: string;
        } & TripCategoryReference
    >;
    difficulty?: 'easy' | 'moderate' | 'challenging' | 'expert';
    duration?: number;
    description?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?:
            'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    highlights?: Array<string>;
    minAge?: number;
    season?: string;
    featuredReview?: {
        quote?: string;
        author?: string;
        source?: string;
    };
    itinerary?: Array<{
        day?: string;
        title?: string;
        description?: string;
        _type: 'itineraryDay';
        _key: string;
    }>;
    itineraryMedia?: {
        video?: {
            asset?: SanityFileAssetReference;
            media?: unknown;
            _type: 'file';
        };
        poster?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
        };
        alt?: string;
    };
    faqs?: Array<
        {
            _key: string;
        } & FaqReference
    >;
    relatedTrips?: Array<
        {
            _key: string;
        } & TripReference
    >;
    photos?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: 'image';
        _key: string;
    }>;
    pricingNotes?: string;
    arcticTripId?: string;
    tagline?: string;
    startingPrice?: string;
    durationLabel?: string;
    subtitle?: string;
    ribbon?: string;
};

export type TripCategory = {
    _id: string;
    _type: 'tripCategory';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
};

export type Activity = {
    _id: string;
    _type: 'activity';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
};

export type River = {
    _id: string;
    _type: 'river';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    description?: string;
    image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
};

export type SanityImagePaletteSwatch = {
    _type: 'sanity.imagePaletteSwatch';
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: 'sanity.imagePalette';
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: 'sanity.imageDimensions';
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type SanityImageMetadata = {
    _type: 'sanity.imageMetadata';
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    thumbHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type SanityFileAsset = {
    _id: string;
    _type: 'sanity.fileAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: 'sanity.assetSourceData';
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageAsset = {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type Geopoint = {
    _type: 'geopoint';
    lat?: number;
    lng?: number;
    alt?: number;
};

export type AllSanitySchemaTypes =
    | SanityImageAssetReference
    | ContentBlock
    | HeroBlock
    | SiteSettings
    | TripReference
    | RiverReference
    | Homepage
    | SanityImageCrop
    | SanityImageHotspot
    | NewsletterSubscriber
    | ContactSubmission
    | Post
    | Slug
    | Page
    | Faq
    | ActivityReference
    | TripCategoryReference
    | SanityFileAssetReference
    | FaqReference
    | Trip
    | TripCategory
    | Activity
    | River
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageMetadata
    | SanityFileAsset
    | SanityAssetSourceData
    | SanityImageAsset
    | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: allTripsQuery
// Query: *[_type == "trip"] | order(name asc) {    _id,    name,    slug,    difficulty,    duration,    pricingNotes,    arcticTripId,    tagline,    subtitle,    ribbon,    startingPrice,    durationLabel,    "river": river->{ name, slug },    "activities": activities[]->{ name, slug },    "categories": categories[]->{ name, slug },    "mainImage": photos[0]  }
export type AllTripsQueryResult = Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    difficulty: 'challenging' | 'easy' | 'expert' | 'moderate' | null;
    duration: number | null;
    pricingNotes: string | null;
    arcticTripId: string | null;
    tagline: string | null;
    subtitle: string | null;
    ribbon: string | null;
    startingPrice: string | null;
    durationLabel: string | null;
    river: {
        name: string | null;
        slug: Slug | null;
    } | null;
    activities: Array<{
        name: string | null;
        slug: Slug | null;
    }> | null;
    categories: Array<{
        name: string | null;
        slug: Slug | null;
    }> | null;
    mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: 'image';
        _key: string;
    } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: tripBySlugQuery
// Query: *[_type == "trip" && slug.current == $slug][0] {    _id,    name,    slug,    difficulty,    duration,    description,    highlights,    photos,    pricingNotes,    arcticTripId,    tagline,    subtitle,    ribbon,    startingPrice,    durationLabel,    "river": river->{ _id, name, slug, description, image },    "activities": activities[]->{ _id, name, slug },    "categories": categories[]->{ _id, name, slug },    minAge,    season,    featuredReview,    itinerary,    "itineraryMedia": itineraryMedia{      "videoUrl": video.asset->url,      poster,      alt    },    "faqs": faqs[]->{ _id, question, answer, category },    "relatedTrips": select(      count(relatedTrips) > 0 => relatedTrips[]->{        _id, name, slug, tagline, subtitle, ribbon, startingPrice,        durationLabel, difficulty,        "category": categories[0]->name,        "image": photos[0]      },      *[_type == "trip" && slug.current != $slug &&        (river._ref == ^.river._ref ||         count(activities[@._ref in ^.^.activities[]._ref]) > 0)      ] | order(name asc) [0...3] {        _id, name, slug, tagline, subtitle, ribbon, startingPrice,        durationLabel, difficulty,        "category": categories[0]->name,        "image": photos[0]      }    )  }
export type TripBySlugQueryResult = {
    _id: string;
    name: string | null;
    slug: Slug | null;
    difficulty: 'challenging' | 'easy' | 'expert' | 'moderate' | null;
    duration: number | null;
    description: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?:
            'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }> | null;
    highlights: Array<string> | null;
    photos: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: 'image';
        _key: string;
    }> | null;
    pricingNotes: string | null;
    arcticTripId: string | null;
    tagline: string | null;
    subtitle: string | null;
    ribbon: string | null;
    startingPrice: string | null;
    durationLabel: string | null;
    river: {
        _id: string;
        name: string | null;
        slug: Slug | null;
        description: string | null;
        image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
        } | null;
    } | null;
    activities: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
    }> | null;
    categories: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
    }> | null;
    minAge: number | null;
    season: string | null;
    featuredReview: {
        quote?: string;
        author?: string;
        source?: string;
    } | null;
    itinerary: Array<{
        day?: string;
        title?: string;
        description?: string;
        _type: 'itineraryDay';
        _key: string;
    }> | null;
    itineraryMedia: {
        videoUrl: string | null;
        poster: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
        } | null;
        alt: string | null;
    } | null;
    faqs: Array<{
        _id: string;
        question: string | null;
        answer: Array<{
            children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: 'span';
                _key: string;
            }>;
            style?:
                | 'blockquote'
                | 'h1'
                | 'h2'
                | 'h3'
                | 'h4'
                | 'h5'
                | 'h6'
                | 'normal';
            listItem?: 'bullet' | 'number';
            markDefs?: Array<{
                href?: string;
                _type: 'link';
                _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
        }> | null;
        category:
            | 'booking'
            | 'cancellation'
            | 'general'
            | 'safety'
            | 'trip-preparation'
            | null;
    }> | null;
    relatedTrips: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
        tagline: string | null;
        subtitle: string | null;
        ribbon: string | null;
        startingPrice: string | null;
        durationLabel: string | null;
        difficulty: 'challenging' | 'easy' | 'expert' | 'moderate' | null;
        category: string | null;
        image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
        } | null;
    }> | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: allRiversQuery
// Query: *[_type == "river"] | order(name asc) {    _id,    name,    slug,    description,    image  }
export type AllRiversQueryResult = Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    description: string | null;
    image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: riverBySlugQuery
// Query: *[_type == "river" && slug.current == $slug][0] {    _id,    name,    slug,    description,    image,    "trips": *[_type == "trip" && river._ref == ^._id] | order(name asc) {      _id,      name,      slug,      tagline,      subtitle,      ribbon,      startingPrice,      durationLabel,      difficulty,      "category": categories[0]->name,      "image": photos[0]    }  }
export type RiverBySlugQueryResult = {
    _id: string;
    name: string | null;
    slug: Slug | null;
    description: string | null;
    image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    } | null;
    trips: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
        tagline: string | null;
        subtitle: string | null;
        ribbon: string | null;
        startingPrice: string | null;
        durationLabel: string | null;
        difficulty: 'challenging' | 'easy' | 'expert' | 'moderate' | null;
        category: string | null;
        image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
        } | null;
    }>;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: allActivitiesQuery
// Query: *[_type == "activity"] | order(name asc) {    _id,    name,    slug,    description,    image  }
export type AllActivitiesQueryResult = Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    description: string | null;
    image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: activityBySlugQuery
// Query: *[_type == "activity" && slug.current == $slug][0] {    _id,    name,    slug,    description,    image,    "trips": *[_type == "trip" && references(^._id)] | order(name asc) {      _id,      name,      slug,      tagline,      subtitle,      ribbon,      startingPrice,      durationLabel,      difficulty,      "category": categories[0]->name,      "image": photos[0]    }  }
export type ActivityBySlugQueryResult = {
    _id: string;
    name: string | null;
    slug: Slug | null;
    description: string | null;
    image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    } | null;
    trips: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
        tagline: string | null;
        subtitle: string | null;
        ribbon: string | null;
        startingPrice: string | null;
        durationLabel: string | null;
        difficulty: 'challenging' | 'easy' | 'expert' | 'moderate' | null;
        category: string | null;
        image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
        } | null;
    }>;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: allFaqsQuery
// Query: *[_type == "faq"] | order(category asc, order asc) {    _id,    question,    answer,    category  }
export type AllFaqsQueryResult = Array<{
    _id: string;
    question: string | null;
    answer: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?:
            'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }> | null;
    category:
        | 'booking'
        | 'cancellation'
        | 'general'
        | 'safety'
        | 'trip-preparation'
        | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    phone,    email,    address,    socialLinks,    reviews  }
export type SiteSettingsQueryResult = {
    phone: string | null;
    email: string | null;
    address: string | null;
    socialLinks: {
        facebook?: string;
        instagram?: string;
        youtube?: string;
        tiktok?: string;
    } | null;
    reviews: {
        ratingLabel?: string;
        tripadvisorUrl?: string;
        googleUrl?: string;
    } | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post"] | order(publishedAt desc) {    _id,    title,    slug,    excerpt,    mainImage,    publishedAt,    category  }
export type AllPostsQueryResult = Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    excerpt: string | null;
    mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    } | null;
    publishedAt: string | null;
    category: 'conservation' | 'culture-history' | 'trip-prep' | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    slug,    excerpt,    mainImage,    publishedAt,    category,    body  }
export type PostBySlugQueryResult = {
    _id: string;
    title: string | null;
    slug: Slug | null;
    excerpt: string | null;
    mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    } | null;
    publishedAt: string | null;
    category: 'conservation' | 'culture-history' | 'trip-prep' | null;
    body: Array<
        | {
              children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: 'span';
                  _key: string;
              }>;
              style?:
                  | 'blockquote'
                  | 'h1'
                  | 'h2'
                  | 'h3'
                  | 'h4'
                  | 'h5'
                  | 'h6'
                  | 'normal';
              listItem?: 'bullet' | 'number';
              markDefs?: Array<{
                  href?: string;
                  _type: 'link';
                  _key: string;
              }>;
              level?: number;
              _type: 'block';
              _key: string;
          }
        | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: 'image';
              _key: string;
          }
    > | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    slug,    content  }
export type PageBySlugQueryResult = {
    _id: string;
    title: string | null;
    slug: Slug | null;
    content: Array<
        | ({
              _key: string;
          } & ContentBlock)
        | ({
              _key: string;
          } & HeroBlock)
    > | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: homepageQuery
// Query: *[_type == "homepage"][0] {    heroHeading,    heroImage,    "heroImageAlt": heroImage.alt,    heroCtaText,    heroCtaLink,    "featuredTrips": featuredTrips[]->{      _id,      name,      slug,      tagline,      subtitle,      ribbon,      startingPrice,      durationLabel,      difficulty,      "category": categories[0]->name,      "image": photos[0]    },    storyBody,    storyImageLeft,    storyImagePortrait,    storyCtaText,    storyCtaLink,    "rivers": rivers[]->{      _id,      name,      slug,      image    },    learnContent[]{      _key,      title,      image,      link,      isVideo    }  }
export type HomepageQueryResult = {
    heroHeading: string | null;
    heroImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
    } | null;
    heroImageAlt: string | null;
    heroCtaText: string | null;
    heroCtaLink: string | null;
    featuredTrips: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
        tagline: string | null;
        subtitle: string | null;
        ribbon: string | null;
        startingPrice: string | null;
        durationLabel: string | null;
        difficulty: 'challenging' | 'easy' | 'expert' | 'moderate' | null;
        category: string | null;
        image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: 'image';
            _key: string;
        } | null;
    }> | null;
    storyBody: string | null;
    storyImageLeft: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    } | null;
    storyImagePortrait: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    } | null;
    storyCtaText: string | null;
    storyCtaLink: string | null;
    rivers: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
        image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
        } | null;
    }> | null;
    learnContent: Array<{
        _key: string;
        title: string | null;
        image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
        } | null;
        link: string | null;
        isVideo: boolean | null;
    }> | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
    interface SanityQueries {
        '\n  *[_type == "trip"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    difficulty,\n    duration,\n    pricingNotes,\n    arcticTripId,\n    tagline,\n    subtitle,\n    ribbon,\n    startingPrice,\n    durationLabel,\n    "river": river->{ name, slug },\n    "activities": activities[]->{ name, slug },\n    "categories": categories[]->{ name, slug },\n    "mainImage": photos[0]\n  }\n': AllTripsQueryResult;
        '\n  *[_type == "trip" && slug.current == $slug][0] {\n    _id,\n    name,\n    slug,\n    difficulty,\n    duration,\n    description,\n    highlights,\n    photos,\n    pricingNotes,\n    arcticTripId,\n    tagline,\n    subtitle,\n    ribbon,\n    startingPrice,\n    durationLabel,\n    "river": river->{ _id, name, slug, description, image },\n    "activities": activities[]->{ _id, name, slug },\n    "categories": categories[]->{ _id, name, slug },\n    minAge,\n    season,\n    featuredReview,\n    itinerary,\n    "itineraryMedia": itineraryMedia{\n      "videoUrl": video.asset->url,\n      poster,\n      alt\n    },\n    "faqs": faqs[]->{ _id, question, answer, category },\n    "relatedTrips": select(\n      count(relatedTrips) > 0 => relatedTrips[]->{\n        _id, name, slug, tagline, subtitle, ribbon, startingPrice,\n        durationLabel, difficulty,\n        "category": categories[0]->name,\n        "image": photos[0]\n      },\n      *[_type == "trip" && slug.current != $slug &&\n        (river._ref == ^.river._ref ||\n         count(activities[@._ref in ^.^.activities[]._ref]) > 0)\n      ] | order(name asc) [0...3] {\n        _id, name, slug, tagline, subtitle, ribbon, startingPrice,\n        durationLabel, difficulty,\n        "category": categories[0]->name,\n        "image": photos[0]\n      }\n    )\n  }\n': TripBySlugQueryResult;
        '\n  *[_type == "river"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    description,\n    image\n  }\n': AllRiversQueryResult;
        '\n  *[_type == "river" && slug.current == $slug][0] {\n    _id,\n    name,\n    slug,\n    description,\n    image,\n    "trips": *[_type == "trip" && river._ref == ^._id] | order(name asc) {\n      _id,\n      name,\n      slug,\n      tagline,\n      subtitle,\n      ribbon,\n      startingPrice,\n      durationLabel,\n      difficulty,\n      "category": categories[0]->name,\n      "image": photos[0]\n    }\n  }\n': RiverBySlugQueryResult;
        '\n  *[_type == "activity"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    description,\n    image\n  }\n': AllActivitiesQueryResult;
        '\n  *[_type == "activity" && slug.current == $slug][0] {\n    _id,\n    name,\n    slug,\n    description,\n    image,\n    "trips": *[_type == "trip" && references(^._id)] | order(name asc) {\n      _id,\n      name,\n      slug,\n      tagline,\n      subtitle,\n      ribbon,\n      startingPrice,\n      durationLabel,\n      difficulty,\n      "category": categories[0]->name,\n      "image": photos[0]\n    }\n  }\n': ActivityBySlugQueryResult;
        '\n  *[_type == "faq"] | order(category asc, order asc) {\n    _id,\n    question,\n    answer,\n    category\n  }\n': AllFaqsQueryResult;
        '\n  *[_type == "siteSettings"][0] {\n    phone,\n    email,\n    address,\n    socialLinks,\n    reviews\n  }\n': SiteSettingsQueryResult;
        '\n  *[_type == "post"] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage,\n    publishedAt,\n    category\n  }\n': AllPostsQueryResult;
        '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage,\n    publishedAt,\n    category,\n    body\n  }\n': PostBySlugQueryResult;
        '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    content\n  }\n': PageBySlugQueryResult;
        '\n  *[_type == "homepage"][0] {\n    heroHeading,\n    heroImage,\n    "heroImageAlt": heroImage.alt,\n    heroCtaText,\n    heroCtaLink,\n    "featuredTrips": featuredTrips[]->{\n      _id,\n      name,\n      slug,\n      tagline,\n      subtitle,\n      ribbon,\n      startingPrice,\n      durationLabel,\n      difficulty,\n      "category": categories[0]->name,\n      "image": photos[0]\n    },\n    storyBody,\n    storyImageLeft,\n    storyImagePortrait,\n    storyCtaText,\n    storyCtaLink,\n    "rivers": rivers[]->{\n      _id,\n      name,\n      slug,\n      image\n    },\n    learnContent[]{\n      _key,\n      title,\n      image,\n      link,\n      isVideo\n    }\n  }\n': HomepageQueryResult;
    }
}
